---
# tasks file for postfix

- name: Execute role tasks
  block:

    - name: Include assert.yml
      ansible.builtin.include_tasks: assert.yml
    
    - name: Include postfix.yml
      ansible.builtin.include_tasks: postfix.yml
    
    - name: Include aliases.yml
      ansible.builtin.include_tasks: aliases.yml

  become: yes
